[build.environment]
  # Node on Netlify's image is too old - this fixes build error.
  NODE_VERSION = "18"

[[redirects]]
  from = "/imoveis"
  to = "https://www.zapimoveis.com.br/imobiliaria/100695/"

[[redirects]]
  from = "/*"
  to = "https://romildocorretor.com.br/"
